// eslint-disable-next-line import/prefer-default-export
export const data = [
  {
    imageURL:
      "https://imagenes.elpais.com/resizer/uH9SGrtzfjp_NHQBiwyNsCesEn0=/1960x0/filters:focal(3632x1874:3642x1884)/cloudfront-eu-central-1.images.arcpublishing.com/prisa/2SYY662JDFGLLCAEM6VWAGV6BY.jpg",
    artist: "Delfin Hasta el fin",
    location: "Madison Square Garden",
    city: "New York",
    seat: 10,
    direction: "Fake Street 12345",
    country: "United States",
    type: "concierto",
    date: "2019-12-9",
    tickets_available: 100,
    tickets_left: 90,
    id: "1",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere metus id felis fermentum, suscipit congue nibh commodo. Aliquam erat volutpat. Aenean a metus vitae eros accumsan sollicitudin. Praesent lacinia augue a quam placerat, a ornare elit aliquet. Mauris dignissim nisl est. Sed commodo aliquet mauris, maximus dapibus diam lacinia a. Sed sapien felis, ullamcorper fermentum malesuada at, commodo eget metus. Duis eget est lobortis, viverra augue vitae, auctor odio. Cras luctus odio est, non blandit magna tempus sit amet. Sed nec est ultrices, posuere lacus sed, dapibus ex. Sed vulputate vitae nulla quis viverra.",
    price: 0.01,
  },
  {
    imageURL:
      "https://s1.ticketm.net/dam/a/dfa/25d31984-65fb-428a-80a7-cc979012edfa_1238711_TABLET_LANDSCAPE_LARGE_16_9.jpg?width=450&height=255&fit=crop&auto=webp",
    artist: "Sepultura",
    location: "Estadio Central",
    city: "Buenos Aires",
    seat: 10,
    direction: "Fake Street 12345",
    country: "Argentina",
    type: "concierto",
    date: "2019-12-9",
    tickets_available: 100,
    tickets_left: 90,
    id: "2",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere metus id felis fermentum, suscipit congue nibh commodo. Aliquam erat volutpat. Aenean a metus vitae eros accumsan sollicitudin. Praesent lacinia augue a quam placerat, a ornare elit aliquet. Mauris dignissim nisl est. Sed commodo aliquet mauris, maximus dapibus diam lacinia a. Sed sapien felis, ullamcorper fermentum malesuada at, commodo eget metus. Duis eget est lobortis, viverra augue vitae, auctor odio. Cras luctus odio est, non blandit magna tempus sit amet. Sed nec est ultrices, posuere lacus sed, dapibus ex. Sed vulputate vitae nulla quis viverra.",
    price: 0.04,
  },
  {
    imageURL:
      "https://s1.ticketm.net/dam/a/895/a991762b-5b7b-42d0-99b2-b37978675895_1179381_TABLET_LANDSCAPE_LARGE_16_9.jpg?width=450&height=255&fit=crop&auto=webp",
    artist: "Katy Perry",
    location: "Auditorio Maxx",
    city: "Cali",
    seat: 10,
    direction: "Fake Street 12345",
    country: "United States",
    type: "concierto",
    date: "2019-12-9",
    tickets_available: 200,
    tickets_left: 70,
    id: "3",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere metus id felis fermentum, suscipit congue nibh commodo. Aliquam erat volutpat. Aenean a metus vitae eros accumsan sollicitudin. Praesent lacinia augue a quam placerat, a ornare elit aliquet. Mauris dignissim nisl est. Sed commodo aliquet mauris, maximus dapibus diam lacinia a. Sed sapien felis, ullamcorper fermentum malesuada at, commodo eget metus. Duis eget est lobortis, viverra augue vitae, auctor odio. Cras luctus odio est, non blandit magna tempus sit amet. Sed nec est ultrices, posuere lacus sed, dapibus ex. Sed vulputate vitae nulla quis viverra.",
    price: 0.015,
  },
  {
    imageURL:
      "https://s1.ticketm.net/dam/a/1e8/1a5a6417-5a9b-4dd1-ac1e-8aa162fb91e8_1572181_TABLET_LANDSCAPE_LARGE_16_9.jpg?width=450&height=255&fit=crop&auto=webp",
    artist: "Weird Al Yankovic",
    location: "Bar Las palomas",
    city: "Bogotá",
    seat: 10,
    direction: "Fake Street 12345",
    country: "Colombia",
    type: "concierto",
    date: "2019-12-9",
    tickets_available: 110,
    tickets_left: 40,
    id: "4",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere metus id felis fermentum, suscipit congue nibh commodo. Aliquam erat volutpat. Aenean a metus vitae eros accumsan sollicitudin. Praesent lacinia augue a quam placerat, a ornare elit aliquet. Mauris dignissim nisl est. Sed commodo aliquet mauris, maximus dapibus diam lacinia a. Sed sapien felis, ullamcorper fermentum malesuada at, commodo eget metus. Duis eget est lobortis, viverra augue vitae, auctor odio. Cras luctus odio est, non blandit magna tempus sit amet. Sed nec est ultrices, posuere lacus sed, dapibus ex. Sed vulputate vitae nulla quis viverra.",
    price: 0.05,
  },
  {
    imageURL:
      "https://s1.ticketm.net/dam/a/f5c/44687510-aac6-46ad-b517-907bdeb03f5c_50561_TABLET_LANDSCAPE_LARGE_16_9.jpg?width=450&height=255&fit=crop&auto=webp",
    artist: "Fatboy Slim",
    location: "Auditorio Imaginario",
    city: "Bogotá",
    seat: 10,
    direction: "Fake Street 12345",
    country: "Colombia",
    type: "concierto",
    date: "2019-12-9",
    tickets_available: 110,
    tickets_left: 30,
    id: "5",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere metus id felis fermentum, suscipit congue nibh commodo. Aliquam erat volutpat. Aenean a metus vitae eros accumsan sollicitudin. Praesent lacinia augue a quam placerat, a ornare elit aliquet. Mauris dignissim nisl est. Sed commodo aliquet mauris, maximus dapibus diam lacinia a. Sed sapien felis, ullamcorper fermentum malesuada at, commodo eget metus. Duis eget est lobortis, viverra augue vitae, auctor odio. Cras luctus odio est, non blandit magna tempus sit amet. Sed nec est ultrices, posuere lacus sed, dapibus ex. Sed vulputate vitae nulla quis viverra.",
    price: 0.005,
  },
  {
    imageURL:
      "https://s1.ticketm.net/dam/a/979/abed8b8f-592c-4fd8-b2c9-d69d71818979_1236341_TABLET_LANDSCAPE_LARGE_16_9.jpg?width=450&height=255&fit=crop&auto=webp",
    artist: "Pixies",
    location: "Estadio Mundial",
    city: "Buenos Aires",
    seat: 10,
    direction: "Fake Street 12345",
    country: "Argentina",
    type: "concierto",
    date: "2019-12-9",
    tickets_available: 110,
    tickets_left: 30,
    id: "6",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere metus id felis fermentum, suscipit congue nibh commodo. Aliquam erat volutpat. Aenean a metus vitae eros accumsan sollicitudin. Praesent lacinia augue a quam placerat, a ornare elit aliquet. Mauris dignissim nisl est. Sed commodo aliquet mauris, maximus dapibus diam lacinia a. Sed sapien felis, ullamcorper fermentum malesuada at, commodo eget metus. Duis eget est lobortis, viverra augue vitae, auctor odio. Cras luctus odio est, non blandit magna tempus sit amet. Sed nec est ultrices, posuere lacus sed, dapibus ex. Sed vulputate vitae nulla quis viverra.",
    price: 0.045,
  },
  {
    imageURL:
      "https://s1.ticketm.net/dam/a/839/17ecf37d-82b3-4703-833c-3632cb7fa839_1449041_TABLET_LANDSCAPE_LARGE_16_9.jpg?width=450&height=255&fit=crop&auto=webp",
    artist: "Kiss",
    location: "Tu mente",
    city: "Cali",
    seat: 10,
    direction: "Fake Street 12345",
    country: "Colombia",
    type: "concierto",
    date: "2019-12-9",
    tickets_available: 110,
    tickets_left: 30,
    id: "7",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere metus id felis fermentum, suscipit congue nibh commodo. Aliquam erat volutpat. Aenean a metus vitae eros accumsan sollicitudin. Praesent lacinia augue a quam placerat, a ornare elit aliquet. Mauris dignissim nisl est. Sed commodo aliquet mauris, maximus dapibus diam lacinia a. Sed sapien felis, ullamcorper fermentum malesuada at, commodo eget metus. Duis eget est lobortis, viverra augue vitae, auctor odio. Cras luctus odio est, non blandit magna tempus sit amet. Sed nec est ultrices, posuere lacus sed, dapibus ex. Sed vulputate vitae nulla quis viverra.",
    price: 0.005,
  },
  {
    imageURL:
      "https://s1.ticketm.net/dam/a/d76/d1194e52-fe26-4ba5-9bd7-0cbe94bf1d76_1574941_TABLET_LANDSCAPE_LARGE_16_9.jpg?width=450&height=255&fit=crop&auto=webp",
    artist: "Olivia Rodrigo",
    location: "Tu mente",
    city: "Cali",
    seat: 10,
    direction: "Fake Street 12345",
    country: "Colombia",
    type: "concierto",
    date: "2019-12-9",
    tickets_available: 110,
    tickets_left: 30,
    id: "8",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere metus id felis fermentum, suscipit congue nibh commodo. Aliquam erat volutpat. Aenean a metus vitae eros accumsan sollicitudin. Praesent lacinia augue a quam placerat, a ornare elit aliquet. Mauris dignissim nisl est. Sed commodo aliquet mauris, maximus dapibus diam lacinia a. Sed sapien felis, ullamcorper fermentum malesuada at, commodo eget metus. Duis eget est lobortis, viverra augue vitae, auctor odio. Cras luctus odio est, non blandit magna tempus sit amet. Sed nec est ultrices, posuere lacus sed, dapibus ex. Sed vulputate vitae nulla quis viverra.",
    price: 0.035,
  },
  {
    imageURL:
      "https://s1.ticketm.net/dam/c/df8/81eadad8-4449-412e-a2b1-3d8bbb78edf8_106181_TABLET_LANDSCAPE_LARGE_16_9.jpg?width=450&height=255&fit=crop&auto=webp",
    artist: "Raime",
    location: "Bar El tufo",
    city: "Bogotá",
    seat: 10,
    direction: "Fake Street 12345",
    country: "Colombia",
    type: "concierto",
    date: "2019-12-9",
    tickets_available: 110,
    tickets_left: 30,
    id: "9",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere metus id felis fermentum, suscipit congue nibh commodo. Aliquam erat volutpat. Aenean a metus vitae eros accumsan sollicitudin. Praesent lacinia augue a quam placerat, a ornare elit aliquet. Mauris dignissim nisl est. Sed commodo aliquet mauris, maximus dapibus diam lacinia a. Sed sapien felis, ullamcorper fermentum malesuada at, commodo eget metus. Duis eget est lobortis, viverra augue vitae, auctor odio. Cras luctus odio est, non blandit magna tempus sit amet. Sed nec est ultrices, posuere lacus sed, dapibus ex. Sed vulputate vitae nulla quis viverra.",
    price: 0.025,
  },
  {
    imageURL:
      "https://s1.ticketm.net/dam/a/13a/b69f7e85-dde8-4c2b-9fa2-b6630507a13a_387491_TABLET_LANDSCAPE_LARGE_16_9.jpg?width=450&height=255&fit=crop&auto=webp",
    artist: "Milli Vanilli",
    location: "Matik Matik",
    city: "Bogotá",
    seat: 10,
    direction: "Fake Street 12345",
    country: "Colombia",
    type: "concierto",
    date: "2019-12-9",
    tickets_available: 110,
    tickets_left: 30,
    id: "10",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere metus id felis fermentum, suscipit congue nibh commodo. Aliquam erat volutpat. Aenean a metus vitae eros accumsan sollicitudin. Praesent lacinia augue a quam placerat, a ornare elit aliquet. Mauris dignissim nisl est. Sed commodo aliquet mauris, maximus dapibus diam lacinia a. Sed sapien felis, ullamcorper fermentum malesuada at, commodo eget metus. Duis eget est lobortis, viverra augue vitae, auctor odio. Cras luctus odio est, non blandit magna tempus sit amet. Sed nec est ultrices, posuere lacus sed, dapibus ex. Sed vulputate vitae nulla quis viverra.",
    price: 0.015,
  },
  {
    imageURL:
      "https://s1.ticketm.net/dam/a/592/2c596688-a3ae-4d7e-9d9f-b310f350a592_1208391_TABLET_LANDSCAPE_LARGE_16_9.jpg?width=450&height=255&fit=crop&auto=webp",
    artist: "Babymetal",
    location: "Café Tin",
    city: "Buenos Aires",
    seat: 10,
    direction: "Fake Street 12345",
    country: "Argentina",
    type: "concierto",
    date: "2019-12-9",
    tickets_available: 110,
    tickets_left: 30,
    id: "11",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere metus id felis fermentum, suscipit congue nibh commodo. Aliquam erat volutpat. Aenean a metus vitae eros accumsan sollicitudin. Praesent lacinia augue a quam placerat, a ornare elit aliquet. Mauris dignissim nisl est. Sed commodo aliquet mauris, maximus dapibus diam lacinia a. Sed sapien felis, ullamcorper fermentum malesuada at, commodo eget metus. Duis eget est lobortis, viverra augue vitae, auctor odio. Cras luctus odio est, non blandit magna tempus sit amet. Sed nec est ultrices, posuere lacus sed, dapibus ex. Sed vulputate vitae nulla quis viverra.",
    price: 0.01,
  },
  {
    imageURL:
      "https://s1.ticketm.net/dam/a/f1c/076a52d9-7d7c-44ad-b24e-cc47e51c6f1c_971431_TABLET_LANDSCAPE_LARGE_16_9.jpg?width=450&height=255&fit=crop&auto=webp",
    artist: "Blackpink",
    location: "Estadio El Campín",
    city: "Bogotá",
    seat: 10,
    direction: "Fake Street 12345",
    country: "Colombia",
    type: "concierto",
    date: "2019-12-9",
    tickets_available: 110,
    tickets_left: 30,
    id: "12",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere metus id felis fermentum, suscipit congue nibh commodo. Aliquam erat volutpat. Aenean a metus vitae eros accumsan sollicitudin. Praesent lacinia augue a quam placerat, a ornare elit aliquet. Mauris dignissim nisl est. Sed commodo aliquet mauris, maximus dapibus diam lacinia a. Sed sapien felis, ullamcorper fermentum malesuada at, commodo eget metus. Duis eget est lobortis, viverra augue vitae, auctor odio. Cras luctus odio est, non blandit magna tempus sit amet. Sed nec est ultrices, posuere lacus sed, dapibus ex. Sed vulputate vitae nulla quis viverra.",
    price: 0.02,

  },
  {
    imageURL:
      "https://s1.ticketm.net/dam/a/3e2/6a93fa81-f9b7-4c59-90df-b732cab543e2_1296091_TABLET_LANDSCAPE_LARGE_16_9.jpg?width=450&height=255&fit=crop&auto=webp",
    artist: "Arca",
    location: "Estadio Superior",
    city: "Cali",
    seat: 10,
    direction: "Fake Street 12345",
    country: "Colombia",
    type: "concierto",
    date: "2019-12-9",
    tickets_available: 110,
    tickets_left: 30,
    id: "13",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere metus id felis fermentum, suscipit congue nibh commodo. Aliquam erat volutpat. Aenean a metus vitae eros accumsan sollicitudin. Praesent lacinia augue a quam placerat, a ornare elit aliquet. Mauris dignissim nisl est. Sed commodo aliquet mauris, maximus dapibus diam lacinia a. Sed sapien felis, ullamcorper fermentum malesuada at, commodo eget metus. Duis eget est lobortis, viverra augue vitae, auctor odio. Cras luctus odio est, non blandit magna tempus sit amet. Sed nec est ultrices, posuere lacus sed, dapibus ex. Sed vulputate vitae nulla quis viverra.",
    price: 0.02,
  },
  {
    imageURL:
      "https://s1.ticketm.net/dam/c/fbc/b293c0ad-c904-4215-bc59-8d7f2414dfbc_106141_TABLET_LANDSCAPE_LARGE_16_9.jpg?width=450&height=255&fit=crop&auto=webp",
    artist: "Los Punsetes",
    location: "Estadio Superior",
    city: "Cali",
    seat: 10,
    direction: "Fake Street 12345",
    country: "Colombia",
    type: "concierto",
    date: "2019-12-9",
    tickets_available: 110,
    tickets_left: 30,
    id: "13",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere metus id felis fermentum, suscipit congue nibh commodo. Aliquam erat volutpat. Aenean a metus vitae eros accumsan sollicitudin. Praesent lacinia augue a quam placerat, a ornare elit aliquet. Mauris dignissim nisl est. Sed commodo aliquet mauris, maximus dapibus diam lacinia a. Sed sapien felis, ullamcorper fermentum malesuada at, commodo eget metus. Duis eget est lobortis, viverra augue vitae, auctor odio. Cras luctus odio est, non blandit magna tempus sit amet. Sed nec est ultrices, posuere lacus sed, dapibus ex. Sed vulputate vitae nulla quis viverra.",
    price: 0.02,
  },
  {
    imageURL:
      "https://s1.ticketm.net/dam/a/3b9/d81d3922-8082-4012-9696-cecc3b6683b9_1591641_TABLET_LANDSCAPE_LARGE_16_9.jpg?width=450&height=255&fit=crop&auto=webp",
    artist: "Animal Collective",
    location: "Estadio Superior",
    city: "Cali",
    seat: 10,
    direction: "Fake Street 12345",
    country: "Colombia",
    type: "concierto",
    date: "2019-12-9",
    tickets_available: 110,
    tickets_left: 30,
    id: "14",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere metus id felis fermentum, suscipit congue nibh commodo. Aliquam erat volutpat. Aenean a metus vitae eros accumsan sollicitudin. Praesent lacinia augue a quam placerat, a ornare elit aliquet. Mauris dignissim nisl est. Sed commodo aliquet mauris, maximus dapibus diam lacinia a. Sed sapien felis, ullamcorper fermentum malesuada at, commodo eget metus. Duis eget est lobortis, viverra augue vitae, auctor odio. Cras luctus odio est, non blandit magna tempus sit amet. Sed nec est ultrices, posuere lacus sed, dapibus ex. Sed vulputate vitae nulla quis viverra.",
    price: 0.02,
  },
];
